Jessica donuts - consents
Sensedia/massadedados pull request #30
Opened 2021-06-25 22:25 UTC by fabricenunes

2021-06-28 18:27 UTC, abenderd requested changes
- [x] Em F2_Consentimento/get-consents-{consentId}/get-consents-consentId-17.1.json ajustar link para contemplar o consentId do arquivo, atualmente ele está com valor de outro json.

2021-06-29 17:59 UTC, JessicaTerada commented on F2_Consentimento/get-consents-{consentId}/get-consents-consentId-17.1.json
> +        "requestDateTime": "2021-05-28T11:04:00Z"
Atualizar o requestDateTime para o range do consents

2021-06-29 20:07 UTC, JessicaTerada commented on F2_Consentimento/get-consents-{consentId}/get-consents-consentId-17.1.json
> +        "self": "https://api.itau/open-banking/consents/v1/consents/urn:bb:BB96825411"
Fix do consentId

2021-06-29 20:11 UTC, fabricenunes commented on F2_Consentimento/get-consents-{consentId}/get-consents-consentId-17.1.json
> +        "self": "https://api.itau/open-banking/consents/v1/consents/urn:bb:BB96825411"
Ajustado

2021-06-29 20:15 UTC, fabricenunes commented on F2_Consentimento/get-consents-{consentId}/get-consents-consentId-17.1.json
> +        "requestDateTime": "2021-05-28T11:04:00Z"
Ajustado

2021-06-29 20:17 UTC, JessicaTerada approved these changes

2021-06-29 20:17 UTC, merged