Carvalho eletronica - consents
Sensedia/massadedados pull request #31
Opened 2021-06-25 22:28 UTC by fabricenunes

2021-06-28 18:28 UTC, abenderd requested changes
Em F2_Consentimento/get-consents-{consentId}/get-consents-consentId-18.1.json ajustar o consentId informado no parâmetro link.

2021-06-29 17:14 UTC, liliancavalet commented
> Em F2_Consentimento/get-consents-{consentId}/get-consents-consentId-18.1.json ajustar o consentId informado no parâmetro link.

Feito

2021-06-29 17:58 UTC, JessicaTerada approved these changes

2021-06-29 20:41 UTC, JessicaTerada approved these changes

2021-06-29 20:41 UTC, merged