Aline contabilidade - consents
Sensedia/massadedados pull request #36
Opened 2021-06-25 22:37 UTC by fabricenunes

2021-06-28 18:34 UTC, abenderd requested changes
Ajustar consentId nos parametros link.

2021-06-29 17:53 UTC, JessicaTerada approved these changes

2021-06-29 19:58 UTC, fabricenunes commented
Ajustado o link

2021-06-29 20:36 UTC, JessicaTerada approved these changes

2021-06-29 20:36 UTC, merged